### ISSUE TITLE
Define when to version data files

### ISSUE THREAD

**Issue by anelles** [nu-radio/NuRadioReco#1]
Versioning data files? 
-- there is a version defined in ARIANNAio, but unclear when to count up the versioning
-- count minor up, when new parameters are added?
-- count major up, when what?

**Comment by cg-laser** [comment]
minor ups are for 'minor' changes in the file format, e.g., if new quantities are added (with new getter/setter) functions. If just a parameter is added to the parameters dictionary, we do not need to count up the file format. In case of a minor update, old files should still be readable. The new parameters are then just not present in the data structure. 

major ups are if we change the file structure completely. E.g. at some point we might want to get rid of pickle and do a customized serialization for improved security.

**Comment by anelles** [comment]
It seems like there is currently only a VERSION for the ARIANNA files. 
Shouldn't we also need something for the reco and sim files?

**Comment by anelles** [comment]
I think we should have a wiki page regarding this, as soon as we have done our first release. What do think @cg-laser ?
Also so that people know where to change the version.

**Comment by cg-laser** [comment]
yes we should make a wiki page. 

I'm not sure what will be the best place. Probably we have 3 different places:

1) add version to top level __init__.py (this seems to be the standard for python projects)
2) add a corresponding tag to git
3) have a separate file version. Often the file version remains constant but the NuRadioReco version can go up. But then old files are still readable. But if we change the file version we should also make a new NuRadioReco version.

**Comment by anelles** [comment]
@cg-laser can you add to: https://github.com/nu-radio/NuRadioReco/wiki/Documentation

**Comment by anelles** [comment]
Documentation has been added.
