### ISSUE TITLE
Store list of used modules

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioReco#118]
I think it would be a good idea to be able see which modules were used in the reconstruction of an event. This could be done as a parameter in the stationParameters (this would also allow to keep track for the station and the sim_station separately). That parameter would just store a list and each module adds its name at the end when it is running.
If implement this along with #76 , this should not be too much work to implement.

**Comment by anelles** [comment]
@cg-laser, if I am not totally mistaken, we have implemented this and we can close this issue, right?
