### ISSUE TITLE
keep track of filters/amps for noise calculation

### ISSUE THREAD

**Issue by cg-laser** [nu-radio/NuRadioReco#130]
For most NuRadioMC simulations, the noise level is specified using the noise temperature. The realized RMS noise then depends on the bandwidth of the detector and amplification. The current implementation is cumbersome and error prone: The user needs to specify the bandwidth in the config file (i.e. calculate it manually for the filters that are applied in the detector simulation). 

I want to change the code such that NuRadioMC can calculate the bandwidth automatically. Therefore, the filter and amplifier modules need to register their frequency response to some central place. As the bandwidth needs to be known prior to the first execution of the run method (e.g. when noise is added the RMS needs to be scaled according to the final bandwidth), the filter characteristic needs to be specified in the begin and not the run method. 

We could keep track of all filters in the base_trace class. 

I'm not sure if this is the best possible implementation, and it would require some changes to the structure. What do you think?

**Comment by cg-laser** [comment]
a better way might be to do a dry run first. Before the actual simulation starts, the detector simulation is executed once on a dummy event to determine the filters. 
then we can keep everything in the run method

**Comment by daniel-zid** [comment]
Maybe we could specify filters in the config file like we specify the bandwidth? Then, the steering file would just read the type of filter and apply it accordingly. I know it's not an ideal long-term solution and we may lose flexibility. But just to give an idea.

**Comment by cg-laser** [comment]
I guess this will be too complicated for the config file. Specifying the detector description via a python steering is a good way, but we need to add to save the information of filtering somehow. 
BTW: It is also required to save the module order because we need to know at which point noise is being added. @christophwelling did you already start with the "module storing" #118 ?

**Comment by cg-laser** [comment]
The next problem is how to store the filter. Numerically, i.e., array of amplitudes for certain frequencies? This might get problematic because at different stages of the reconstruction have a different sampling rate (or trace length). Better is to provide a function
`get_filter(frequencies, channel_id, **kwargs)` that can be called with the same kwargs as the `run` method. Then we can build up any combination of filters for any frequency range and resolution.

With the new module registry the module instances are saved such that a later call to the `get_filter` method is possible (see #132).
