### ISSUE TITLE
eventWriter produces empty files

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioReco#133]
If the last event the eventWriter saves pushes the filesize over the maximum, the eventWriter will create a new file and write the header into it, but never fill it with any events. Trying to read this file will crash the eventReader.

I see 2 ways to solve this:
1. Stop the eventWriter from producing such files
2. Make sure the eventReader recognizes such files and skips them

Number 1 would be more elegent, but I think 2 is easier to implement (just look at file size)

**Comment by anelles** [comment]
I am voting for an elegant solution ...

**Comment by christophwelling** [comment]
Fixed in PR #129
