### ISSUE TITLE
Run NuRadioMC tests on NuRadioReco?

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioReco#148]
Sometimes changes in NuRadioMC don't break their own unit test but the ones in NuRadioReco and vice versa. An easy was to avoid this is to also run the NuRadioMC unit tests in NuRadioReco (and the NuRadioReco unit tests in NuRadioMC). We download both repositories anyway when testing, so adding these to the test shouldn't be too hard. The tests will just take a bit longer.

**Comment by cg-laser** [comment]
I'm ok with adding NuRadioReco tests to NuRadioMC, but NuRadioReco is independent of NuRadioMC. It would be better to make the NuRadioReco tests independent of NuRadioMC. I guess this dependency was only added because it was easier that way. But instead we could just add a *nur file to start from. It its too large, we could even host it somewhere else.

**Comment by christophwelling** [comment]
I think having some Reco checks including MC makes sense. Some changes in NuRadioReco might break the writing of MC simulation results into .nur files and if that happens it is better to catch it before the change is pushed onto the master.

**Comment by anelles** [comment]
I am a bit indifferent to adding more tests. It is of course good to test more -- and I don't actually mind that Reco and MC test each other. However, if it takes too long, no one like waiting for the tests to finish and it is additional work to add them. Not high priority, but maybe something for a boring train ride or so.

**Comment by christophwelling** [comment]
Adding them is pretty easy. We download both repositories anyway, so we just need to list the scripts in the travis file.
Wasn't there an option to have different tests on branches and pull requests? Then we could just test the other module on pull requests only. We have a 24h waiting policy, so waiting for the tests would not be an issue in this case.

**Comment by anelles** [comment]
We only run the tests on pull requests anyway. Feel free to add them to thet travis file.  And let's see how it goes. We can always take them back out, if things are too slow.
