### ISSUE TITLE
Position for sim stations

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioReco#156]
Currently the simStation has the get/set position methods that allow it to give the simStation a different position than the one in the detector description. Since this makes the station's position somewhat ambiguous, I suggest we remove them.
It is now possible to add stations to the genericDetector at run time and store them in the event files. This way we could handle reading in CoREAS showers (which I think is what these methods were for originally). Doing it this way makes it clear where the station actually is and keeps the code structure clean, since we won't have to store detector info in the event structure.
Are there any reservations against doing it this way?

**Comment by fschlueter** [comment]
Hi,
I initially thought about adding the generic stations to the detector description in the CoREAS reader module. But then you somehow mix stuff (simulation and detector description) and it might get less transparent. but i agree one can do so. I still dont like the limitation to store one event per file. and the position is the only thing which changes. Would it not be possible to just store the sim stations with position and the stations with the id of the station in the detector description and create the detector stations per event on the fly when reading ?

**Comment by anelles** [comment]
Maybe I am missing the question. But shouldn't then the get/set _position change the generic detector per event rather than the position at a station?

**Comment by cg-laser** [comment]
I think the reasonable way is to set up the detector correctly as originally suggested by @christophwelling . But we need to distinguish two types of coreas simulation studies:
1. create a virtual detector resembling the antenna positions of a coreas simulation
2. a coreas simulation for an existent detector layout (which is what we do at the moment, then we either simulated exactly a detector layout or we choose the position in coreas that is closest to the actual station position). 
We should have different reader modules for the two cases. 

@christophwelling @fschlueter Is it true that we can only have one detector per file? I thought you implemented it such that in principle every event can have a different detector. Then @fschlueter reservations don't hold and we can implement it as suggested.

**Comment by christophwelling** [comment]
The problem is that there is one detector description per file. If we want to have several detectors, the problem is how to figure out which detector belongs to which event. The only way around this problem that I can think of is to give the stations in different events different IDs, then everything would be consistent.

**Comment by christophwelling** [comment]
If the detector setup in the CoREAS simulation is the same as a real detector, then the second case is already covered. The reader will create the stations at the correct positions and you can just use the detector description of the existing detector (and write that one into the file if you want).

**Comment by fschlueter** [comment]
Hi,
for the first case i think an optimal solution is what i proposed before. We store one generic detector description per file (I think it is unlikely to have lets say different antenna type for virtual stations within one simulation library, e.g., one file) without the station positions which are stored in the sim_stations. Then when can create one the fly the full detector description including the positions. It is understandable what i mean?
Cheers

**Comment by christophwelling** [comment]
Unfortunately not. If you open multiple files, NuRadioRecoio will have a detector instance for every file (I circumvent the singleton class by calling __new__ explicitly, by the way) and since it remembers which file the last event came from, it knows which detector to return. I don't see an easy way to do this per event, unless store a detector for every event, but I don't think we want to do that.
Should we maybe have a NuRadioReco call tomorrow and discuss this?

**Comment by fschlueter** [comment]
Hi @cg-laser,
No, at the moment the readCoREASShower just returns an event with the run() method. In the example file read_full_CoREAS_shower.py the detector is created in the run loop and "added" to the file via the eventWriter. I also would not do this because it gets in-transparent what the  readCoREASShower.

**Comment by cg-laser** [comment]
but this means the user needs to have this inside knowledge of how to create a detector on-the-fly... I would favor to have this within the coreas reader. 

But this example shows another problem: When reading in the nur files again, they don't contain the correct detector description...

My feeling is that the only correct way is to allow storing a detector description per event. Can't we just create a new detector instance every time a detector is part of the event in the data file?

**Comment by fschlueter** [comment]
If we have a detector for each event we would have a get like evt.get_detector(), right? In this case the getter would create a detector describtion from the generic detector stored in the nur file and the positions of the sim_stations in the evt. If you want to add the detector with the reader module we can do so too.
