### ISSUE TITLE
Station trace_start_time

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioReco#21]
With the removal of the efield trace from the station class, the trace_start_time property no longer makes sense for a station and was removed when base_station lost its inheritance from base_trace. We need to decide where station-wide timing changes should be stored now and make sure that this is done properly

**Comment by cg-laser** [comment]
We could add a quantity explicitly to base_trace
`get/set_relative_station_time()`
However, this might be confusing as the user needs to check both the relative station time as well as the relative channel time. Therefore, I would opt for storing everything in the channel/trace start time. The code is then a little longer (loop over all channels) but I think it is less confusing for the user.

**Comment by anelles** [comment]
What is the status on this one? Have we decided on how to store timing?

**Comment by christophwelling** [comment]
I think this is a larger issue, since we also need to figure out how to handle trace_start_times in E-fields. Since these would also be affected by station-wide timing changes I think it is safer to handle this at the station level.
Also, does the python datetime object even support nanoseconds? Internally it seems to only store microseconds, so I doubt it. So something like station_time_nanoseconds (similar to how it is handled in Offline) would make sense.
However I would prefer to first get the CR energy reconstruction stuff done before working on this.

**Comment by anelles** [comment]
No worries, just wondered what the status was. 
Indeed, we need to address timing a bit broader, no rush.

**Comment by christophwelling** [comment]
Fixed in pull request #59
