### ISSUE TITLE
divide by zero in SNR calculation (signal reconstructor)

### ISSUE THREAD

**Issue by cg-laser** [nu-radio/NuRadioReco#38]
divide by zero is not catched in signal reconstructor module, see trace below:

/Users/cglaser/software/NuRadioReco/NuRadioReco/modules/channelSignalReconstructor.py:102: RuntimeWarning: invalid value encountered in double_scalars
  SNR['integrated_power'] /= (noise_int / self.__signal_window_start)
/Users/cglaser/software/NuRadioReco/NuRadioReco/modules/channelSignalReconstructor.py:106: RuntimeWarning: invalid value encountered in double_scalars
  SNR['peak_2_peak_amplitude'] /= noise_rms
/Users/cglaser/software/NuRadioReco/NuRadioReco/modules/channelSignalReconstructor.py:109: RuntimeWarning: invalid value encountered in double_scalars
  SNR['peak_amplitude'] = np.max(np.abs(trace[signal_window_mask])) / noise_rms

These corner cases should be caught and handled properly. If it is not possible to calculate the SNR, the SNR should be set to np.nan.

**Comment by anelles** [comment]
Is addressed in pull request #39
