### ISSUE TITLE
Clean up trigger modules

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioReco#54]
**Describe the issue**
It is not easy to see what all the trigger modules do. There is one deprecated trigger module that should be removed if it is not needed any more and in the ARIANNA folder there are the files 'triggerSimulator.py' and 'triggerSimulator2.py' without any explanation what the difference between the two is.

There seems to be a lot of code duplication between the generic trigger modules and the detector-specific triggers. It may be a good idea to use inheritance or a wrapper module here.

**Expected behavior**
It should be clear what the differences between the trigger modules are. Code duplication should be avoided if possible.

**Comment by cg-laser** [comment]
the two ARIANNA trigger module should be identical but implement different numerical methods but both are deprecated, and probably should be removed now. They are still used in the NuRadioMC examples though, cleaning this up at the moment.

**Comment by christophwelling** [comment]
Fixed in pull request #59
