### ISSUE TITLE
Detector info in .nur files

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioReco#55]
**Describe the issue**
.nur files contain no information about what detector description was used to create them. I think this could cause some issues in the long run:
- It is easy to accidentally use the wrong detector, especially when sharing files between people.
- If the detector description changes (i.e. because we found an error) there is no way to know if a file was created with the old or the new description.
- We have to hard-code which detector description to use in the eventbrowser. That is very inconvenient, especially when we want to convince other collaborations to use NuRadioReco. 

**Expected behavior**
I'm not sure how to handle this, we probably don't want to store the entire detector description in the .nur file.
Maybe store the filename in the event? As long as the detector is in NuRadioReco that should work.
Store a hash? That way we would at least know if we use the wrong description.

**Comment by anelles** [comment]
Interesting point. I guess we have always assumed that there was going to be only one central DB server and all local copies will be just that, copies. But indeed as soon as several experiments are using this, this breaks. 
I like the hash idea. Maybe also add a timestamp to the detector (last updated etc.) ?

**Comment by cg-laser** [comment]
in NuRadioMC we save the full detector description just in the hdf5 file. For simulations this is normally a very small file. 
But you're right, in general we don't want to save the full detector description. 

Storing the filename of the DB, or just the unique name, but this is essentially the filename, is a good idea. 
The hash idea is good too but also impractical... often we just add information to the DB. This will change the hash but old files will still be readable. Maybe we can just issue a warning if the hashes don't match? 

We also thought recently about DB versioning. We don't want a new version for every additional element. But we want to be able to reproduce older analyses. Therefore, we currently make a copy of the database before making significant changes to existing elements. This way one could still run an analysis with an older DB version.

**Comment by christophwelling** [comment]
We just had a little discussion about this. We decided that it would be a good idea to allow the user to pass a flag to the eventwriter module to tell it to save the detector description. If the flag is True, the eventwriter will store the description from the .json file as well. The eventwriter knows which stations are in the file and will only save the description for those stations that are actually in the file.
This should still keep event files reasonably small. Anyone still worried about file size still has the option to not store the detector and just do everything by hand.

**Comment by cg-laser** [comment]
sounds good to me. As long as it is optional it is not a problem. And at the moment the detector description is really small. We might want to save the json file as dictionary pickeled into a binary representation to save file size. 
Can we also just save the stations/channels that were present at the event times? station and channel ids are not unique, only in combination with the (de)comission times.

**Comment by anelles** [comment]
Who will pick this up? @cg-laser @christophwelling ?

**Comment by christophwelling** [comment]
I can try, but I am not too familiar with the detector description.
