### ISSUE TITLE
Trigger times not set correctly

### ISSUE THREAD

**Issue by christophwelling** [nu-radio/NuRadioReco#61]
It looks like the trigger simulation modules set the trigger time to the start of the coincidence window around the pulse instead of the pulse.

**Comment by cg-laser** [comment]
this is how defined the trigger time. Taking the middle of the coincidence window will also not be the pulse maximum but the point when the voltage crossed the threshold.

**Comment by cg-laser** [comment]
There is another problem with a different definition. Within a coincidence window (across channels) are potentially many bins (and several) pulses that can cause a trigger. It is not clear to me which one to choose. 

The current definition should resemble what the ARIANNA hardware does.

**Comment by anelles** [comment]
What does the hardware do exactly? I am not sure and I thought what is implemented now is what the hardware does.

**Comment by christophwelling** [comment]
I thought it was set to the time of the first pulse?

**Comment by cg-laser** [comment]
the time of the maximum is not calculated. We only mark the time when the signal passes threshold. And this is how it is implemented now when I'm not mistaken. 
The coincidence window is also not centered around the triggering bin, but the triggering bin is the start of the coincidence window.

**Comment by christophwelling** [comment]
I tested it and if you change the coincidence window, the trigger time will change as well, by half the change in the coincidence window. So it looks like the window is actually centered around the trigger.

**Comment by cg-laser** [comment]
This is weird. Is this on signal only? What trigger module are you talking about? Can you post the exact configuration?

**Comment by christophwelling** [comment]
Yes, it is signal only, cosmic ray events. It happens for both simpleThreshold and highLowThreshold with default settings, except different coincidence windows.

**Comment by cg-laser** [comment]
hmm... the convolution should be such that it counts from a triggering bin onwards. We essentially extend a single trigger bit [0,0,0,0,1,0,0,0,0,0,0,0,0] with as many ones as the trigger window is long [0,0,0,0,0,1,1,1,1,1,1,1,0]. But maybe we are interpreting the resulting absolute time not correctly... the absolute time of a convolution output is always tricky. Maybe it can just be solved by adding 0.5 * coincidence window.

**Comment by cg-laser** [comment]
I fixed the convolution operations. I needed to use the mode 'full' and then cut the output back to the trace length.

For ARIANNA the trigger time is defined as the bin that completes the trigger. Normally this is the single channel trigger time of the second pulse. Thanks @christophwelling for finding this bug.
