### ISSUE TITLE
add base module class

### ISSUE THREAD

**Issue by cg-laser** [nu-radio/NuRadioReco#76]
what do you think about adding a base class from which all modules need to inherit? 
That would allow to have a init function that is the same for all modules where we could define e.g. a unified interface to a logger. Currently this is not consistently treated and just added to the modules if needed.

**Comment by anelles** [comment]
I definitely think the logging needs additional work. A common base module class sounds like a good plan. Would require significant work in overhauling all module though, right?

**Comment by cg-laser** [comment]
we would need to touch every module but only with trivial changes. And we don't break anything. So I would say it it a relatively minor thing. But we would change the interface to modules that already implement a log_level setting.

**Comment by anelles** [comment]
Just to reiterate, everything that is left from this issue is the unified logger, correct?

**Comment by cg-laser** [comment]
We don't have a base module class yet but we register modules via decorators.

**Comment by anelles** [comment]
Ok. It took forever, but I think I finally have somewhat of an understanding of the python logger class. I tihnk it is actually not neccessary to write something fancy with class inheritance from a base module for logging. The logging has inheritance already built in. If you make a logger in the script called 'NuRadioMC' and all loggers in the modules 'NuRadioMC.module' then they automatically inherit all settings (inlcuding the debug level) from the 'NuRadioMC' logger. 
I will make a suggestion of how to change this for all modules. It would still only be a trivial change. May take a while though. 
Was there anything else, that was inteded with this issue apart from fixing logging and debug levels? @cg-laser 
FYI: Using logging.basicConfig() is bad. It creates additional loggers. 3 hours down the drain, but learnt a lot.

**Comment by cg-laser** [comment]
thanks for investigating the logger.

Having a base class would force users to have the same argument names. 
E.g. all run oder begin methods could have a field "logging_level". But 
this might not be that critical depending on how the logging interface 
works. Let's first see what changes you propose to the logger.

Am 21.01.20 um 06:46 schrieb Anna Nelles:
