### ISSUE TITLE
Extension of the filename

### ISSUE THREAD

**Issue by anelles** [nu-radio/NuRadioReco#8]
The filename extension is currently .ari by default. 
Christian and I already discussed that this is no good for future purposes. 
My suggestion would be .nur (for NuRadio obviously, despite it meaning "only" in German)

**Comment by cg-laser** [comment]
As a native German speaker I find that '.nur' sound a little weird. But I don't have any good alternative idea with three letters. Or we could just do *.nu?

**Comment by christophwelling** [comment]
EventWriter now enforces the .nur file ending
